version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_E_TSRR
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: E_TSRR
    ports:
      - "5432:5432"
    volumes:
      - postgres_E_TSRR_data:/var/lib/postgresql/data

volumes:
  postgres_E_TSRR_data: